name: Build Windows exe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 45
    env:
      START_URL: https://raoofictc.com/wp-admin

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm config set fund false audit false
          npm install
      - name: Build Windows installer (NSIS)
        run: npx electron-builder --windows nsis --publish never
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/**
