name: Build Windows exe

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # اگر لاک‌فایل هست: ستاپ نود + کش
      - name: Setup Node (with cache)
        if: ${{ hashFiles('**/package-lock.json') != '' || hashFiles('**/npm-shrinkwrap.json') != '' || hashFiles('**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json
            **/yarn.lock

      # اگر لاک‌فایل نیست: ستاپ نود بدون کش
      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' && hashFiles('**/npm-shrinkwrap.json') == '' && hashFiles('**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # نصب وابستگی‌ها: با ci اگر لاک‌فایل هست، وگرنه install
      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path "package-lock.json" -or Test-Path "npm-shrinkwrap.json") {
            npm ci
          } else {
            npm install
          }

      - name: Build
        run: npm run dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/**
