name: Build Windows exe

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # اگر لاک‌فایل هست → کش npm فعال
      - name: Setup Node (with cache)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json
            **/yarn.lock

      # اگر لاک‌فایل نیست → بدون کش
      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # نصب وابستگی‌ها: npm install (اجازه می‌دهد lock به‌صورت درجا تکمیل شود)
      - name: Install dependencies
        shell: bash
        run: npm install
        # working-directory: .   # اگر پروژه در زیرپوشه است این را تنظیم کن

      - name: Build
        shell: bash
        run: npm run dist
        # working-directory: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/**
          if-no-files-found: error
