name: Build Windows exe (fresh, no cache)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      # پاکسازی کش‌های احتمالی داخلیِ runner برای بیلد کاملاً تازه
      - name: Purge caches (npm & electron & electron-builder)
        shell: pwsh
        run: |
          $npmCache = (npm config get cache)
          if (Test-Path $npmCache) { Remove-Item -Recurse -Force $npmCache }
          npm cache clean --force

          $paths = @(
            "$env:LOCALAPPDATA\electron\Cache",
            "$env:LOCALAPPDATA\electron-builder\Cache",
            "$env:USERPROFILE\AppData\Local\electron\Cache",
            "$env:USERPROFILE\AppData\Local\electron-builder\Cache"
          )
          foreach ($p in $paths) { if (Test-Path $p) { Remove-Item -Recurse -Force $p } }

          $env:ELECTRON_BUILDER_CACHE = "$env:RUNNER_TEMP\eb-cache"
          $env:ELECTRON_CACHE = "$env:RUNNER_TEMP\electron-cache"
          New-Item -ItemType Directory -Force -Path $env:ELECTRON_BUILDER_CACHE | Out-Null
          New-Item -ItemType Directory -Force -Path $env:ELECTRON_CACHE | Out-Null

      # نصب تازه؛ لاک‌فایل اگر هست هم اجازه آپدیت می‌ده
      - name: Install dependencies (fresh)
        shell: bash
        run: npm install --no-audit --no-fund
        # اگر پروژه‌ات در زیرپوشه است، اضافه کن:
        # working-directory: app

      - name: Build
        shell: bash
        env:
          ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/eb-cache
          ELECTRON_CACHE: ${{ runner.temp }}/electron-cache
        run: npm run dist
        # working-directory: app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-${{ github.run_number }}-${{ github.sha }}
          path: dist/**
          if-no-files-found: error
          # اگر زیرپوشه داری:
          # path: app/dist/**
